const actionTypes = {
  LOAD_POKEMONS: 'LOAD_POKEMONS',
  LOAD_POKEMONS_ERROR: 'LOAD_POKEMONS_ERROR',
  LOAD_POKEMON_DETAIL: 'LOAD_POKEMON_DETAIL',
  SET_LOADING: 'SET_LOADING',
};

export default actionTypes;
