const actionTypes = {
  LOAD_POKEMONS: 'LOAD_POKEMONS',
  LOAD_POKEMONS_ERROR: 'LOAD_POKEMONS_ERROR',
  LOAD_POKEMON_DETAIL: 'LOAD_POKEMON_DETAIL',
  LOAD_MOVE_TYPES: 'LOAD_MOVE_TYPES',
  CLEAR_POKEMON_DETAIL: 'CLEAR_POKEMON_DETAIL',
  SET_LOADING: 'SET_LOADING',
  SET_LOADING_MOVES: 'SET_LOADING_MOVES',
  FILTER_POKEMON_LIST: 'FILTER_POKEMON_LIST',
  FILL_POKEMON_DISPLAY_LIST: 'FILL_POKEMON_DISPLAY_LIST',
};

export default actionTypes;
